name: Build Manager (main)

on:
  push:
    branches: [ "main", "ci" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - '.github/workflows/build-manager-common.yml'
      - '.github/workflows/build-ksud.yml'
      - '.github/workflows/build-lkm.yml'
      - '.github/workflows/ddk-lkm.yml'
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/ksud/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'manager/**'
  workflow_call:

jobs:
  build-lkm:
    uses: ./.github/workflows/build-lkm.yml
    secrets: inherit

  build-ksud:
    needs: build-lkm
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            os: ubuntu-latest
          - target: armv7-linux-androideabi
            os: ubuntu-latest
          - target: x86_64-linux-android
            os: ubuntu-latest
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
      os: ${{ matrix.os }}

  build-manager:
    needs: build-ksud
    strategy:
      matrix:
        include:
          - manager_type: normal
          - manager_type: spoofed
    uses: ./.github/workflows/build-manager-common.yml
    secrets: inherit
    with:
      manager_type: ${{ matrix.manager_type }}
